// Copyright 2024 Marek Kraus (@gamelaster)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 150U
#define RP2040_FLASH_GENERIC_03H

// #define MATRIX_UNSELECT_DRIVE_HIGH
#define MATRIX_MASKED
// #define MATRIX_HAS_GHOST

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP28
#define I2C1_SCL_PIN GP29

#define PS2_MOUSE_USE_REMOTE_MODE
